/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
/**
 *
 * @author Dizan
 */
public class MenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuGUI
     */
    
    
    public MenuGUI() {
        super("Proyectos");
        
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
        setSize(width/2+180, height/2+100);		
        setLocationRelativeTo(null);
        
        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        logos();
        setSize(900, 500);
    }
    
     private void logos() {  
        String path = "/img/SEP.png";  
        URL url1 = this.getClass().getResource(path);  
        ImageIcon img = new ImageIcon(url1);  
        labelLogoSep.setIcon(img);
        
        String path2 = "/img/LlogoTec.png";  
        URL url2 = this.getClass().getResource(path2);  
        ImageIcon img2 = new ImageIcon(url2);  
        labelLogoTecNM.setIcon(img2);
        
        String path3 = "/img/calculator.png";  
        URL url3 = this.getClass().getResource(path3);  
        ImageIcon img3 = new ImageIcon(url3);  
        botonProyecto1.setIcon(img3);
        
        String path4 = "/img/dulces.png";  
        URL url4 = this.getClass().getResource(path4);  
        ImageIcon img4 = new ImageIcon(url4);  
        botonProyecto2.setIcon(img4);
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelEncabezado = new javax.swing.JPanel();
        panelLogoSep = new javax.swing.JPanel();
        labelLogoSep = new javax.swing.JLabel();
        panelTitulos = new javax.swing.JPanel();
        labelTecNM = new javax.swing.JLabel();
        labelTecTap = new javax.swing.JLabel();
        labelAsignatura = new javax.swing.JLabel();
        panelLogoTec = new javax.swing.JPanel();
        labelLogoTecNM = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        botonProyecto1 = new javax.swing.JButton();
        botonProyecto2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 36, 96));
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        panelPrincipal.setBackground(new java.awt.Color(0, 36, 96));
        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelEncabezado.setBackground(new java.awt.Color(0, 32, 96));
        panelEncabezado.setLayout(new java.awt.GridBagLayout());

        panelLogoSep.setBackground(new java.awt.Color(0, 32, 96));
        panelLogoSep.add(labelLogoSep);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelEncabezado.add(panelLogoSep, gridBagConstraints);

        panelTitulos.setBackground(new java.awt.Color(0, 32, 96));
        panelTitulos.setLayout(new java.awt.GridBagLayout());

        labelTecNM.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTecNM.setForeground(new java.awt.Color(255, 255, 255));
        labelTecNM.setText("Tecnológico Nacional De México");
        panelTitulos.add(labelTecNM, new java.awt.GridBagConstraints());

        labelTecTap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTecTap.setForeground(new java.awt.Color(255, 255, 255));
        labelTecTap.setText("Instituto Tecnológico de Tapachula");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panelTitulos.add(labelTecTap, gridBagConstraints);

        labelAsignatura.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelAsignatura.setForeground(new java.awt.Color(255, 255, 255));
        labelAsignatura.setText("Lenguajes y Autómatas I");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        panelTitulos.add(labelAsignatura, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelEncabezado.add(panelTitulos, gridBagConstraints);

        panelLogoTec.setBackground(new java.awt.Color(0, 32, 96));
        panelLogoTec.add(labelLogoTecNM);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelEncabezado.add(panelLogoTec, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        panelPrincipal.add(panelEncabezado, gridBagConstraints);

        panelBotones.setBackground(new java.awt.Color(0, 32, 96));
        panelBotones.setLayout(new java.awt.GridBagLayout());

        botonProyecto1.setBackground(new java.awt.Color(0, 51, 51));
        botonProyecto1.setForeground(new java.awt.Color(51, 51, 51));
        botonProyecto1.setBorder(null);
        botonProyecto1.setBorderPainted(false);
        botonProyecto1.setFocusPainted(false);
        botonProyecto1.setOpaque(false);
        botonProyecto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProyecto1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 10, 50);
        panelBotones.add(botonProyecto1, gridBagConstraints);

        botonProyecto2.setBackground(new java.awt.Color(0, 51, 51));
        botonProyecto2.setForeground(new java.awt.Color(51, 51, 51));
        botonProyecto2.setBorder(null);
        botonProyecto2.setFocusPainted(false);
        botonProyecto2.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 10, 50);
        panelBotones.add(botonProyecto2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelPrincipal.add(panelBotones, gridBagConstraints);

        getContentPane().add(panelPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonProyecto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProyecto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonProyecto1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonProyecto1;
    public javax.swing.JButton botonProyecto2;
    private javax.swing.JLabel labelAsignatura;
    private javax.swing.JLabel labelLogoSep;
    private javax.swing.JLabel labelLogoTecNM;
    private javax.swing.JLabel labelTecNM;
    private javax.swing.JLabel labelTecTap;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JPanel panelLogoSep;
    private javax.swing.JPanel panelLogoTec;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTitulos;
    // End of variables declaration//GEN-END:variables
  
}


