/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author Dizan
 */
public class proyecto2GUI extends javax.swing.JFrame {

    /**
     * Creates new form proyecto2GUI
     */
    public proyecto2GUI() {
        super("Maquina de dulces");
        setVisible(true);
       // setSize(900, 600);
        initComponents();
        
    }
    
    private void iconosBotones(){
        String pathPeso = "/img/imgProyecto2/1peso125x125.png";  
        URL urlPeso = this.getClass().getResource(pathPeso);  
        ImageIcon imgPeso = new ImageIcon(urlPeso);  
        botonUnPeso.setIcon(imgPeso);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        fieldSaldo = new javax.swing.JTextField();
        botonDesicion = new javax.swing.JButton();
        labelCambio = new javax.swing.JLabel();
        fieldCambio = new javax.swing.JTextField();
        panelInferior = new javax.swing.JPanel();
        botonUnPeso = new javax.swing.JButton();
        botonDosPesos = new javax.swing.JButton();
        botonCincoPesos = new javax.swing.JButton();
        botonDiezPesos = new javax.swing.JButton();
        botonVeintePesos = new javax.swing.JButton();
        botonElegirProducto = new javax.swing.JButton();
        botonRetirarSaldo = new javax.swing.JButton();
        botonValidar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        panelPrincipal.setBackground(new java.awt.Color(0, 32, 96));
        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelSuperior.setBackground(new java.awt.Color(0, 32, 96));
        panelSuperior.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel superior"));
        panelSuperior.setForeground(new java.awt.Color(51, 51, 51));
        panelSuperior.setLayout(new java.awt.GridBagLayout());

        fieldSaldo.setBackground(new java.awt.Color(0, 0, 0));
        fieldSaldo.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        fieldSaldo.setForeground(new java.awt.Color(192, 0, 0));
        fieldSaldo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldSaldo.setText("005");
        fieldSaldo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        fieldSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSaldoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelSuperior.add(fieldSaldo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        panelSuperior.add(botonDesicion, gridBagConstraints);

        labelCambio.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelCambio.setForeground(new java.awt.Color(255, 255, 255));
        labelCambio.setText("Cambio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        panelSuperior.add(labelCambio, gridBagConstraints);

        fieldCambio.setBackground(new java.awt.Color(0, 0, 0));
        fieldCambio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fieldCambio.setForeground(new java.awt.Color(255, 255, 255));
        fieldCambio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldCambio.setText("000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        panelSuperior.add(fieldCambio, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        panelPrincipal.add(panelSuperior, gridBagConstraints);

        panelInferior.setBackground(new java.awt.Color(0, 32, 96));
        panelInferior.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel inferior"));
        panelInferior.setLayout(new java.awt.GridBagLayout());

        botonUnPeso.setText("$ 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInferior.add(botonUnPeso, gridBagConstraints);

        botonDosPesos.setText("$ 2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInferior.add(botonDosPesos, gridBagConstraints);

        botonCincoPesos.setText("$ 5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInferior.add(botonCincoPesos, gridBagConstraints);

        botonDiezPesos.setText("$ 10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInferior.add(botonDiezPesos, gridBagConstraints);

        botonVeintePesos.setText("$20");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInferior.add(botonVeintePesos, gridBagConstraints);

        botonElegirProducto.setText("Elegir Producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInferior.add(botonElegirProducto, gridBagConstraints);

        botonRetirarSaldo.setText("Retirar sado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInferior.add(botonRetirarSaldo, gridBagConstraints);

        botonValidar.setText("Validar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInferior.add(botonValidar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelPrincipal.add(panelInferior, gridBagConstraints);

        getContentPane().add(panelPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSaldoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proyecto2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proyecto2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proyecto2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proyecto2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proyecto2GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCincoPesos;
    private javax.swing.JButton botonDesicion;
    private javax.swing.JButton botonDiezPesos;
    private javax.swing.JButton botonDosPesos;
    private javax.swing.JButton botonElegirProducto;
    private javax.swing.JButton botonRetirarSaldo;
    private javax.swing.JButton botonUnPeso;
    private javax.swing.JButton botonValidar;
    private javax.swing.JButton botonVeintePesos;
    private javax.swing.JTextField fieldCambio;
    private javax.swing.JTextField fieldSaldo;
    private javax.swing.JLabel labelCambio;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    // End of variables declaration//GEN-END:variables
}
