/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author Dizan
 */
public class proyecto2GUI extends javax.swing.JFrame {

    /**
     * Creates new form proyecto2GUI
     */
    public proyecto2GUI() {
        super("Maquina de dulces");
        
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
        setSize(width/2+180, height-200);		
        setLocationRelativeTo(null);
        initComponents();
        iconosBotones();
        personalizarFuente();
        setSize(600, 600); 
        setVisible(true);
         
    }
    
    private void iconosBotones(){
        
        String pathPeso = "/img/imgProyecto2/1peso125x125.png";  
        URL urlPeso = this.getClass().getResource(pathPeso);  
        ImageIcon imgPeso = new ImageIcon(urlPeso);  
        botonUnPeso.setIcon(imgPeso);
        
        String path2Pesos = "/img/imgProyecto2/2pesos125x125.png";  
        URL url2Pesos = this.getClass().getResource(path2Pesos);  
        ImageIcon img2Pesos = new ImageIcon(url2Pesos);  
        botonDosPesos.setIcon(img2Pesos);
        
        String path5Pesos = "/img/imgProyecto2/5pesos125x125.png";  
        URL url5Pesos = this.getClass().getResource(path5Pesos);  
        ImageIcon img5Pesos = new ImageIcon(url5Pesos);  
        botonCincoPesos.setIcon(img5Pesos);
        
        String path10Pesos = "/img/imgProyecto2/10pesos125x125.png";  
        URL url10Pesos = this.getClass().getResource(path10Pesos);  
        ImageIcon img10Pesos = new ImageIcon(url10Pesos);  
        botonDiezPesos.setIcon(img10Pesos);
        
        String path20Pesos = "/img/imgProyecto2/moneda20pesos125x125.png";  
        URL url20Pesos = this.getClass().getResource(path20Pesos);  
        ImageIcon img20Pesos = new ImageIcon(url20Pesos);  
        botonVeintePesos.setIcon(img20Pesos);
        
        String pathElegirDuldes = "/img/imgProyecto2/elegirDulces.png";  
        URL urlElegirDuldes = this.getClass().getResource(pathElegirDuldes);  
        ImageIcon imgElegirDuldes = new ImageIcon(urlElegirDuldes);  
        botonElegirProducto.setIcon(imgElegirDuldes);
    }
    
    private void personalizarFuente(){
        personalizarFuentes cf = new personalizarFuentes();
        fieldSaldo.setFont(cf.miFuente(1, 96));
        fieldCambio.setFont(cf.miFuente(1, 22));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        fieldSaldo = new javax.swing.JTextField();
        botonDesicion = new javax.swing.JButton();
        labelCambio = new javax.swing.JLabel();
        fieldCambio = new javax.swing.JTextField();
        panelInferior = new javax.swing.JPanel();
        botonUnPeso = new javax.swing.JButton();
        botonDosPesos = new javax.swing.JButton();
        botonCincoPesos = new javax.swing.JButton();
        botonDiezPesos = new javax.swing.JButton();
        botonVeintePesos = new javax.swing.JButton();
        botonElegirProducto = new javax.swing.JButton();
        botonRetirarSaldo = new javax.swing.JButton();
        botonValidar = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        panelPrincipal.setBackground(new java.awt.Color(0, 32, 96));
        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelSuperior.setBackground(new java.awt.Color(0, 32, 96));
        panelSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelSuperior.setForeground(new java.awt.Color(51, 51, 51));
        panelSuperior.setLayout(new java.awt.GridBagLayout());

        fieldSaldo.setEditable(false);
        fieldSaldo.setBackground(new java.awt.Color(0, 0, 0));
        fieldSaldo.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        fieldSaldo.setForeground(new java.awt.Color(192, 0, 0));
        fieldSaldo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldSaldo.setText("00");
        fieldSaldo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        fieldSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSaldoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelSuperior.add(fieldSaldo, gridBagConstraints);

        botonDesicion.setBackground(new java.awt.Color(0, 32, 96));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        panelSuperior.add(botonDesicion, gridBagConstraints);

        labelCambio.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelCambio.setForeground(new java.awt.Color(255, 255, 255));
        labelCambio.setText("Cambio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        panelSuperior.add(labelCambio, gridBagConstraints);

        fieldCambio.setEditable(false);
        fieldCambio.setBackground(new java.awt.Color(0, 0, 0));
        fieldCambio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fieldCambio.setForeground(new java.awt.Color(255, 255, 255));
        fieldCambio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldCambio.setText("00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        panelSuperior.add(fieldCambio, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelPrincipal.add(panelSuperior, gridBagConstraints);

        panelInferior.setBackground(new java.awt.Color(0, 32, 96));
        panelInferior.setLayout(new java.awt.GridBagLayout());

        botonUnPeso.setBackground(new java.awt.Color(0, 32, 96));
        botonUnPeso.setFocusPainted(false);
        botonUnPeso.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInferior.add(botonUnPeso, gridBagConstraints);

        botonDosPesos.setBackground(new java.awt.Color(0, 32, 96));
        botonDosPesos.setToolTipText("");
        botonDosPesos.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInferior.add(botonDosPesos, gridBagConstraints);

        botonCincoPesos.setBackground(new java.awt.Color(0, 32, 96));
        botonCincoPesos.setFocusPainted(false);
        botonCincoPesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCincoPesosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInferior.add(botonCincoPesos, gridBagConstraints);

        botonDiezPesos.setBackground(new java.awt.Color(0, 32, 96));
        botonDiezPesos.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInferior.add(botonDiezPesos, gridBagConstraints);

        botonVeintePesos.setBackground(new java.awt.Color(0, 32, 96));
        botonVeintePesos.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInferior.add(botonVeintePesos, gridBagConstraints);

        botonElegirProducto.setBackground(new java.awt.Color(0, 32, 96));
        botonElegirProducto.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInferior.add(botonElegirProducto, gridBagConstraints);

        botonRetirarSaldo.setBackground(new java.awt.Color(153, 0, 51));
        botonRetirarSaldo.setForeground(new java.awt.Color(255, 255, 255));
        botonRetirarSaldo.setText("Retirar sado");
        botonRetirarSaldo.setBorder(null);
        botonRetirarSaldo.setBorderPainted(false);
        botonRetirarSaldo.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInferior.add(botonRetirarSaldo, gridBagConstraints);

        botonValidar.setBackground(new java.awt.Color(0, 54, 75));
        botonValidar.setForeground(new java.awt.Color(255, 255, 255));
        botonValidar.setText("Validar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInferior.add(botonValidar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPrincipal.add(panelInferior, gridBagConstraints);

        getContentPane().add(panelPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSaldoActionPerformed

    private void botonCincoPesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCincoPesosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCincoPesosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proyecto2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proyecto2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proyecto2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proyecto2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proyecto2GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonCincoPesos;
    public javax.swing.JButton botonDesicion;
    public javax.swing.JButton botonDiezPesos;
    public javax.swing.JButton botonDosPesos;
    public javax.swing.JButton botonElegirProducto;
    public javax.swing.JButton botonRetirarSaldo;
    public javax.swing.JButton botonUnPeso;
    public javax.swing.JButton botonValidar;
    public javax.swing.JButton botonVeintePesos;
    public javax.swing.JTextField fieldCambio;
    public javax.swing.JTextField fieldSaldo;
    private javax.swing.JLabel labelCambio;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    // End of variables declaration//GEN-END:variables
}
