/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.awt.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Dizan
 */
public class proyecto1GUI extends javax.swing.JFrame {
    
      public DefaultTableModel modeloTablaPruebas;
    /**
     * Creates new form proyecto1
     */
    public proyecto1GUI() {
        super("Validación de numeros reales con notación exponencial");
        
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
        setSize(width/2+180, height-200);		
        setLocationRelativeTo(null);
        
        setVisible(true);
        initComponents();
        personalizarComponentes();
        modeloTablaPruebas = (DefaultTableModel) tablaPruebas.getModel() ;
        setSize(900, 600);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void personalizarComponentes(){
       scrollTablaPruebas.getViewport().setBackground(new Color(0,32,96));//Cambia olor del ViewPort fondo de tabla cuando estpa vacio
       botonNumero0.setBackground(new Color(46,117,182));
       botonNumero1.setBackground(new Color(46,117,182));
       botonNumero2.setBackground(new Color(46,117,182));
       botonNumero3.setBackground(new Color(46,117,182));
       botonNumero4.setBackground(new Color(46,117,182));
       botonNumero5.setBackground(new Color(46,117,182));
       botonNumero6.setBackground(new Color(46,117,182));
       botonNumero7.setBackground(new Color(46,117,182));
       botonNumero8.setBackground(new Color(46,117,182));
       botonNumero9.setBackground(new Color(46,117,182));
       C.setBackground(new Color(46,117,182));
       botonMas.setBackground(new Color(46,117,182));
       botonMenos.setBackground(new Color(46,117,182));
       botonIniciar.setBackground(new Color(46,117,182));
       botonExponencial.setBackground(new Color(46,117,182));
       botonPunto.setBackground(new Color(46,117,182));
       
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelSimbolos = new javax.swing.JPanel();
        fieldEntradaSimbolos = new javax.swing.JTextField();
        botonNumero7 = new javax.swing.JButton();
        botonNumero8 = new javax.swing.JButton();
        botonNumero4 = new javax.swing.JButton();
        botonNumero5 = new javax.swing.JButton();
        botonNumero6 = new javax.swing.JButton();
        botonNumero1 = new javax.swing.JButton();
        botonNumero2 = new javax.swing.JButton();
        botonNumero9 = new javax.swing.JButton();
        botonNumero3 = new javax.swing.JButton();
        botonNumero0 = new javax.swing.JButton();
        botonPunto = new javax.swing.JButton();
        C = new javax.swing.JButton();
        botonExponencial = new javax.swing.JButton();
        botonMenos = new javax.swing.JButton();
        botonMas = new javax.swing.JButton();
        botonIniciar = new javax.swing.JButton();
        panelTablaTransicion = new javax.swing.JPanel();
        botonVacio = new javax.swing.JButton();
        botonTablaMas = new javax.swing.JButton();
        botonTablaMenos = new javax.swing.JButton();
        botonTablaDigito = new javax.swing.JButton();
        botonTablaPunto = new javax.swing.JButton();
        botonTablaExponente = new javax.swing.JButton();
        botonTablaFin = new javax.swing.JButton();
        botonTablaQ0 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        panelPruebas = new javax.swing.JPanel();
        scrollTablaPruebas = new javax.swing.JScrollPane();
        tablaPruebas = new javax.swing.JTable();
        panelDecidir = new javax.swing.JPanel();
        botonDecidir = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        panelPrincipal.setBackground(new java.awt.Color(0, 32, 96));
        panelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPrincipal.setForeground(new java.awt.Color(0, 32, 96));
        java.awt.GridBagLayout panelPrincipalLayout = new java.awt.GridBagLayout();
        panelPrincipalLayout.columnWidths = new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        panelPrincipalLayout.rowHeights = new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        panelPrincipal.setLayout(panelPrincipalLayout);

        panelTitulo.setBackground(new java.awt.Color(0, 32, 96));
        panelTitulo.setForeground(java.awt.Color.lightGray);
        panelTitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        panelTitulo.setLayout(new java.awt.GridLayout(1, 0));

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Lenguajes y automatas 1");
        labelTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelTitulo.add(labelTitulo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.weightx = 1.0;
        panelPrincipal.add(panelTitulo, gridBagConstraints);

        panelSimbolos.setBackground(new java.awt.Color(0, 32, 96));
        panelSimbolos.setBorder(new javax.swing.border.MatteBorder(null));
        panelSimbolos.setForeground(java.awt.Color.gray);
        panelSimbolos.setLayout(new java.awt.GridBagLayout());

        fieldEntradaSimbolos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fieldEntradaSimbolos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.weighty = 1.1;
        panelSimbolos.add(fieldEntradaSimbolos, gridBagConstraints);

        botonNumero7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonNumero7.setForeground(new java.awt.Color(255, 255, 255));
        botonNumero7.setText("7");
        botonNumero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 2);
        panelSimbolos.add(botonNumero7, gridBagConstraints);

        botonNumero8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonNumero8.setForeground(new java.awt.Color(255, 255, 255));
        botonNumero8.setText("8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 2);
        panelSimbolos.add(botonNumero8, gridBagConstraints);

        botonNumero4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonNumero4.setForeground(new java.awt.Color(255, 255, 255));
        botonNumero4.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 2);
        panelSimbolos.add(botonNumero4, gridBagConstraints);

        botonNumero5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonNumero5.setForeground(new java.awt.Color(255, 255, 255));
        botonNumero5.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelSimbolos.add(botonNumero5, gridBagConstraints);

        botonNumero6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonNumero6.setForeground(new java.awt.Color(255, 255, 255));
        botonNumero6.setText("6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelSimbolos.add(botonNumero6, gridBagConstraints);

        botonNumero1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonNumero1.setForeground(new java.awt.Color(255, 255, 255));
        botonNumero1.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 2);
        panelSimbolos.add(botonNumero1, gridBagConstraints);

        botonNumero2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonNumero2.setForeground(new java.awt.Color(255, 255, 255));
        botonNumero2.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelSimbolos.add(botonNumero2, gridBagConstraints);

        botonNumero9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonNumero9.setForeground(new java.awt.Color(255, 255, 255));
        botonNumero9.setText("9");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 2);
        panelSimbolos.add(botonNumero9, gridBagConstraints);

        botonNumero3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonNumero3.setForeground(new java.awt.Color(255, 255, 255));
        botonNumero3.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelSimbolos.add(botonNumero3, gridBagConstraints);

        botonNumero0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonNumero0.setForeground(new java.awt.Color(255, 255, 255));
        botonNumero0.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 2);
        panelSimbolos.add(botonNumero0, gridBagConstraints);

        botonPunto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonPunto.setForeground(new java.awt.Color(255, 255, 255));
        botonPunto.setText(".");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelSimbolos.add(botonPunto, gridBagConstraints);

        C.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        C.setForeground(new java.awt.Color(255, 255, 255));
        C.setText("C");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 0);
        panelSimbolos.add(C, gridBagConstraints);

        botonExponencial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonExponencial.setForeground(new java.awt.Color(255, 255, 255));
        botonExponencial.setText("e");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 0);
        panelSimbolos.add(botonExponencial, gridBagConstraints);

        botonMenos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonMenos.setForeground(new java.awt.Color(255, 255, 255));
        botonMenos.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 0);
        panelSimbolos.add(botonMenos, gridBagConstraints);

        botonMas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonMas.setForeground(new java.awt.Color(255, 255, 255));
        botonMas.setText("+");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 0);
        panelSimbolos.add(botonMas, gridBagConstraints);

        botonIniciar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonIniciar.setForeground(new java.awt.Color(255, 255, 255));
        botonIniciar.setText("Iniciar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 170;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panelSimbolos.add(botonIniciar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelPrincipal.add(panelSimbolos, gridBagConstraints);

        panelTablaTransicion.setBackground(new java.awt.Color(0, 32, 96));
        panelTablaTransicion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabla de transición", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        panelTablaTransicion.setLayout(new java.awt.GridLayout(9, 7));

        botonVacio.setBackground(new java.awt.Color(0, 32, 96));
        panelTablaTransicion.add(botonVacio);

        botonTablaMas.setBackground(new java.awt.Color(0, 32, 96));
        botonTablaMas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonTablaMas.setForeground(new java.awt.Color(255, 255, 255));
        botonTablaMas.setText("+");
        panelTablaTransicion.add(botonTablaMas);

        botonTablaMenos.setBackground(new java.awt.Color(0, 32, 96));
        botonTablaMenos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonTablaMenos.setForeground(new java.awt.Color(255, 255, 255));
        botonTablaMenos.setText("-");
        panelTablaTransicion.add(botonTablaMenos);

        botonTablaDigito.setBackground(new java.awt.Color(0, 32, 96));
        botonTablaDigito.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonTablaDigito.setForeground(new java.awt.Color(255, 255, 255));
        botonTablaDigito.setText("d");
        botonTablaDigito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTablaDigitoActionPerformed(evt);
            }
        });
        panelTablaTransicion.add(botonTablaDigito);

        botonTablaPunto.setBackground(new java.awt.Color(0, 32, 96));
        botonTablaPunto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonTablaPunto.setForeground(new java.awt.Color(255, 255, 255));
        botonTablaPunto.setText(".");
        panelTablaTransicion.add(botonTablaPunto);

        botonTablaExponente.setBackground(new java.awt.Color(0, 32, 96));
        botonTablaExponente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonTablaExponente.setForeground(new java.awt.Color(255, 255, 255));
        botonTablaExponente.setText("e");
        panelTablaTransicion.add(botonTablaExponente);

        botonTablaFin.setBackground(new java.awt.Color(0, 32, 96));
        botonTablaFin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonTablaFin.setForeground(new java.awt.Color(255, 255, 255));
        botonTablaFin.setText("FDC");
        panelTablaTransicion.add(botonTablaFin);

        botonTablaQ0.setBackground(new java.awt.Color(0, 32, 96));
        botonTablaQ0.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonTablaQ0.setForeground(new java.awt.Color(255, 255, 255));
        botonTablaQ0.setText("q0");
        panelTablaTransicion.add(botonTablaQ0);

        jButton12.setBackground(new java.awt.Color(0, 32, 96));
        jButton12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("q1");
        panelTablaTransicion.add(jButton12);

        jButton13.setBackground(new java.awt.Color(0, 32, 96));
        jButton13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("q1");
        panelTablaTransicion.add(jButton13);

        jButton14.setBackground(new java.awt.Color(0, 32, 96));
        jButton14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("q2");
        panelTablaTransicion.add(jButton14);

        jButton15.setBackground(new java.awt.Color(0, 32, 96));
        jButton15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("E");
        panelTablaTransicion.add(jButton15);

        jButton16.setBackground(new java.awt.Color(0, 32, 96));
        jButton16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("E");
        panelTablaTransicion.add(jButton16);

        jButton17.setBackground(new java.awt.Color(0, 32, 96));
        jButton17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("ERROR");
        panelTablaTransicion.add(jButton17);

        jButton18.setBackground(new java.awt.Color(0, 32, 96));
        jButton18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("q1");
        panelTablaTransicion.add(jButton18);

        jButton19.setBackground(new java.awt.Color(0, 32, 96));
        jButton19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("E");
        panelTablaTransicion.add(jButton19);

        jButton20.setBackground(new java.awt.Color(0, 32, 96));
        jButton20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("E");
        panelTablaTransicion.add(jButton20);

        jButton21.setBackground(new java.awt.Color(0, 32, 96));
        jButton21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("q2");
        panelTablaTransicion.add(jButton21);

        jButton22.setBackground(new java.awt.Color(0, 32, 96));
        jButton22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("E");
        panelTablaTransicion.add(jButton22);

        jButton23.setBackground(new java.awt.Color(0, 32, 96));
        jButton23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setText("E");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        panelTablaTransicion.add(jButton23);

        jButton24.setBackground(new java.awt.Color(0, 32, 96));
        jButton24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton24.setForeground(new java.awt.Color(255, 255, 255));
        jButton24.setText("ERROR");
        panelTablaTransicion.add(jButton24);

        jButton25.setBackground(new java.awt.Color(0, 32, 96));
        jButton25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setText("q2");
        panelTablaTransicion.add(jButton25);

        jButton26.setBackground(new java.awt.Color(0, 32, 96));
        jButton26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton26.setForeground(new java.awt.Color(255, 255, 255));
        jButton26.setText("E");
        panelTablaTransicion.add(jButton26);

        jButton27.setBackground(new java.awt.Color(0, 32, 96));
        jButton27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton27.setForeground(new java.awt.Color(255, 255, 255));
        jButton27.setText("E");
        panelTablaTransicion.add(jButton27);

        jButton28.setBackground(new java.awt.Color(0, 32, 96));
        jButton28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton28.setForeground(new java.awt.Color(255, 255, 255));
        jButton28.setText("q2");
        panelTablaTransicion.add(jButton28);

        jButton29.setBackground(new java.awt.Color(0, 32, 96));
        jButton29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton29.setForeground(new java.awt.Color(255, 255, 255));
        jButton29.setText("q3");
        panelTablaTransicion.add(jButton29);

        jButton30.setBackground(new java.awt.Color(0, 32, 96));
        jButton30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton30.setForeground(new java.awt.Color(255, 255, 255));
        jButton30.setText("E");
        panelTablaTransicion.add(jButton30);

        jButton31.setBackground(new java.awt.Color(0, 32, 96));
        jButton31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton31.setForeground(new java.awt.Color(255, 255, 255));
        jButton31.setText("ERROR");
        panelTablaTransicion.add(jButton31);

        jButton32.setBackground(new java.awt.Color(0, 32, 96));
        jButton32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton32.setForeground(new java.awt.Color(255, 255, 255));
        jButton32.setText("q3");
        panelTablaTransicion.add(jButton32);

        jButton33.setBackground(new java.awt.Color(0, 32, 96));
        jButton33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton33.setForeground(new java.awt.Color(255, 255, 255));
        jButton33.setText("E");
        panelTablaTransicion.add(jButton33);

        jButton34.setBackground(new java.awt.Color(0, 32, 96));
        jButton34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton34.setForeground(new java.awt.Color(255, 255, 255));
        jButton34.setText("E");
        panelTablaTransicion.add(jButton34);

        jButton35.setBackground(new java.awt.Color(0, 32, 96));
        jButton35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton35.setForeground(new java.awt.Color(255, 255, 255));
        jButton35.setText("q4");
        panelTablaTransicion.add(jButton35);

        jButton36.setBackground(new java.awt.Color(0, 32, 96));
        jButton36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton36.setForeground(new java.awt.Color(255, 255, 255));
        jButton36.setText("E");
        panelTablaTransicion.add(jButton36);

        jButton37.setBackground(new java.awt.Color(0, 32, 96));
        jButton37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton37.setForeground(new java.awt.Color(255, 255, 255));
        jButton37.setText("q5");
        panelTablaTransicion.add(jButton37);

        jButton38.setBackground(new java.awt.Color(0, 32, 96));
        jButton38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton38.setForeground(new java.awt.Color(255, 255, 255));
        jButton38.setText("ERROR");
        panelTablaTransicion.add(jButton38);

        jButton39.setBackground(new java.awt.Color(0, 32, 96));
        jButton39.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton39.setForeground(new java.awt.Color(255, 255, 255));
        jButton39.setText("q4");
        panelTablaTransicion.add(jButton39);

        jButton40.setBackground(new java.awt.Color(0, 32, 96));
        jButton40.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton40.setForeground(new java.awt.Color(255, 255, 255));
        jButton40.setText("E");
        panelTablaTransicion.add(jButton40);

        jButton41.setBackground(new java.awt.Color(0, 32, 96));
        jButton41.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton41.setForeground(new java.awt.Color(255, 255, 255));
        jButton41.setText("E");
        panelTablaTransicion.add(jButton41);

        jButton42.setBackground(new java.awt.Color(0, 32, 96));
        jButton42.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton42.setForeground(new java.awt.Color(255, 255, 255));
        jButton42.setText("q4");
        panelTablaTransicion.add(jButton42);

        jButton43.setBackground(new java.awt.Color(0, 32, 96));
        jButton43.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton43.setForeground(new java.awt.Color(255, 255, 255));
        jButton43.setText("E");
        panelTablaTransicion.add(jButton43);

        jButton44.setBackground(new java.awt.Color(0, 32, 96));
        jButton44.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton44.setForeground(new java.awt.Color(255, 255, 255));
        jButton44.setText("E");
        panelTablaTransicion.add(jButton44);

        jButton45.setBackground(new java.awt.Color(0, 32, 96));
        jButton45.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton45.setForeground(new java.awt.Color(255, 255, 255));
        jButton45.setText("A");
        panelTablaTransicion.add(jButton45);

        jButton46.setBackground(new java.awt.Color(0, 32, 96));
        jButton46.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton46.setForeground(new java.awt.Color(255, 255, 255));
        jButton46.setText("q5");
        panelTablaTransicion.add(jButton46);

        jButton47.setBackground(new java.awt.Color(0, 32, 96));
        jButton47.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton47.setForeground(new java.awt.Color(255, 255, 255));
        jButton47.setText("q6");
        panelTablaTransicion.add(jButton47);

        jButton48.setBackground(new java.awt.Color(0, 32, 96));
        jButton48.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton48.setForeground(new java.awt.Color(255, 255, 255));
        jButton48.setText("q6");
        panelTablaTransicion.add(jButton48);

        jButton49.setBackground(new java.awt.Color(0, 32, 96));
        jButton49.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton49.setForeground(new java.awt.Color(255, 255, 255));
        jButton49.setText("q7");
        panelTablaTransicion.add(jButton49);

        jButton50.setBackground(new java.awt.Color(0, 32, 96));
        jButton50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton50.setForeground(new java.awt.Color(255, 255, 255));
        jButton50.setText("E");
        panelTablaTransicion.add(jButton50);

        jButton51.setBackground(new java.awt.Color(0, 32, 96));
        jButton51.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton51.setForeground(new java.awt.Color(255, 255, 255));
        jButton51.setText("E");
        panelTablaTransicion.add(jButton51);

        jButton52.setBackground(new java.awt.Color(0, 32, 96));
        jButton52.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton52.setForeground(new java.awt.Color(255, 255, 255));
        jButton52.setText("ERROR");
        panelTablaTransicion.add(jButton52);

        jButton53.setBackground(new java.awt.Color(0, 32, 96));
        jButton53.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton53.setForeground(new java.awt.Color(255, 255, 255));
        jButton53.setText("q6");
        panelTablaTransicion.add(jButton53);

        jButton54.setBackground(new java.awt.Color(0, 32, 96));
        jButton54.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton54.setForeground(new java.awt.Color(255, 255, 255));
        jButton54.setText("E");
        panelTablaTransicion.add(jButton54);

        jButton55.setBackground(new java.awt.Color(0, 32, 96));
        jButton55.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton55.setForeground(new java.awt.Color(255, 255, 255));
        jButton55.setText("E");
        panelTablaTransicion.add(jButton55);

        jButton56.setBackground(new java.awt.Color(0, 32, 96));
        jButton56.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton56.setForeground(new java.awt.Color(255, 255, 255));
        jButton56.setText("q7");
        jButton56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton56ActionPerformed(evt);
            }
        });
        panelTablaTransicion.add(jButton56);

        jButton57.setBackground(new java.awt.Color(0, 32, 96));
        jButton57.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton57.setForeground(new java.awt.Color(255, 255, 255));
        jButton57.setText("E");
        panelTablaTransicion.add(jButton57);

        jButton58.setBackground(new java.awt.Color(0, 32, 96));
        jButton58.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton58.setForeground(new java.awt.Color(255, 255, 255));
        jButton58.setText("E");
        panelTablaTransicion.add(jButton58);

        jButton59.setBackground(new java.awt.Color(0, 32, 96));
        jButton59.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton59.setForeground(new java.awt.Color(255, 255, 255));
        jButton59.setText("ERROR");
        panelTablaTransicion.add(jButton59);

        jButton60.setBackground(new java.awt.Color(0, 32, 96));
        jButton60.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton60.setForeground(new java.awt.Color(255, 255, 255));
        jButton60.setText("q7");
        panelTablaTransicion.add(jButton60);

        jButton61.setBackground(new java.awt.Color(0, 32, 96));
        jButton61.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton61.setForeground(new java.awt.Color(255, 255, 255));
        jButton61.setText("E");
        panelTablaTransicion.add(jButton61);

        jButton62.setBackground(new java.awt.Color(0, 32, 96));
        jButton62.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton62.setForeground(new java.awt.Color(255, 255, 255));
        jButton62.setText("E");
        panelTablaTransicion.add(jButton62);

        jButton63.setBackground(new java.awt.Color(0, 32, 96));
        jButton63.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton63.setForeground(new java.awt.Color(255, 255, 255));
        jButton63.setText("q7");
        panelTablaTransicion.add(jButton63);

        jButton64.setBackground(new java.awt.Color(0, 32, 96));
        jButton64.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton64.setForeground(new java.awt.Color(255, 255, 255));
        jButton64.setText("E");
        panelTablaTransicion.add(jButton64);

        jButton65.setBackground(new java.awt.Color(0, 32, 96));
        jButton65.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton65.setForeground(new java.awt.Color(255, 255, 255));
        jButton65.setText("E");
        panelTablaTransicion.add(jButton65);

        jButton66.setBackground(new java.awt.Color(0, 32, 96));
        jButton66.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton66.setForeground(new java.awt.Color(255, 255, 255));
        jButton66.setText("A");
        panelTablaTransicion.add(jButton66);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelPrincipal.add(panelTablaTransicion, gridBagConstraints);

        panelPruebas.setBackground(new java.awt.Color(0, 32, 96));
        panelPruebas.setForeground(new java.awt.Color(0, 32, 96));
        panelPruebas.setLayout(new java.awt.GridLayout(1, 1));

        scrollTablaPruebas.setBackground(new java.awt.Color(0, 32, 96));
        scrollTablaPruebas.setBorder(null);
        scrollTablaPruebas.setForeground(java.awt.SystemColor.control);

        tablaPruebas.setBackground(new java.awt.Color(0, 32, 96));
        tablaPruebas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tablaPruebas.setForeground(new java.awt.Color(255, 255, 255));
        tablaPruebas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Estado", "S", "Entrada"
            }
        ));
        tablaPruebas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaPruebas.setGridColor(new java.awt.Color(204, 204, 204));
        tablaPruebas.setSelectionBackground(new java.awt.Color(0, 64, 142));
        tablaPruebas.setSelectionForeground(new java.awt.Color(0, 153, 153));
        scrollTablaPruebas.setViewportView(tablaPruebas);
        if (tablaPruebas.getColumnModel().getColumnCount() > 0) {
            tablaPruebas.getColumnModel().getColumn(0).setMinWidth(40);
            tablaPruebas.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        panelPruebas.add(scrollTablaPruebas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelPrincipal.add(panelPruebas, gridBagConstraints);

        panelDecidir.setBackground(new java.awt.Color(0, 32, 96));
        panelDecidir.setLayout(new java.awt.GridLayout(1, 1));

        botonDecidir.setBackground(new java.awt.Color(0, 36, 92));
        botonDecidir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonDecidir.setForeground(new java.awt.Color(255, 255, 255));
        botonDecidir.setEnabled(false);
        panelDecidir.add(botonDecidir);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelPrincipal.add(panelDecidir, gridBagConstraints);

        getContentPane().add(panelPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonTablaDigitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTablaDigitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonTablaDigitoActionPerformed

    private void jButton56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton56ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void botonNumero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNumero7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proyecto1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proyecto1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proyecto1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proyecto1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proyecto1GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton C;
    public javax.swing.JButton botonDecidir;
    public javax.swing.JButton botonExponencial;
    public javax.swing.JButton botonIniciar;
    public javax.swing.JButton botonMas;
    public javax.swing.JButton botonMenos;
    public javax.swing.JButton botonNumero0;
    public javax.swing.JButton botonNumero1;
    public javax.swing.JButton botonNumero2;
    public javax.swing.JButton botonNumero3;
    public javax.swing.JButton botonNumero4;
    public javax.swing.JButton botonNumero5;
    public javax.swing.JButton botonNumero6;
    public javax.swing.JButton botonNumero7;
    public javax.swing.JButton botonNumero8;
    public javax.swing.JButton botonNumero9;
    public javax.swing.JButton botonPunto;
    public javax.swing.JButton botonTablaDigito;
    public javax.swing.JButton botonTablaExponente;
    public javax.swing.JButton botonTablaFin;
    public javax.swing.JButton botonTablaMas;
    public javax.swing.JButton botonTablaMenos;
    public javax.swing.JButton botonTablaPunto;
    public javax.swing.JButton botonTablaQ0;
    public javax.swing.JButton botonVacio;
    public javax.swing.JTextField fieldEntradaSimbolos;
    public javax.swing.JButton jButton12;
    public javax.swing.JButton jButton13;
    public javax.swing.JButton jButton14;
    public javax.swing.JButton jButton15;
    public javax.swing.JButton jButton16;
    public javax.swing.JButton jButton17;
    public javax.swing.JButton jButton18;
    public javax.swing.JButton jButton19;
    public javax.swing.JButton jButton20;
    public javax.swing.JButton jButton21;
    public javax.swing.JButton jButton22;
    public javax.swing.JButton jButton23;
    public javax.swing.JButton jButton24;
    public javax.swing.JButton jButton25;
    public javax.swing.JButton jButton26;
    public javax.swing.JButton jButton27;
    public javax.swing.JButton jButton28;
    public javax.swing.JButton jButton29;
    public javax.swing.JButton jButton30;
    public javax.swing.JButton jButton31;
    public javax.swing.JButton jButton32;
    public javax.swing.JButton jButton33;
    public javax.swing.JButton jButton34;
    public javax.swing.JButton jButton35;
    public javax.swing.JButton jButton36;
    public javax.swing.JButton jButton37;
    public javax.swing.JButton jButton38;
    public javax.swing.JButton jButton39;
    public javax.swing.JButton jButton40;
    public javax.swing.JButton jButton41;
    public javax.swing.JButton jButton42;
    public javax.swing.JButton jButton43;
    public javax.swing.JButton jButton44;
    public javax.swing.JButton jButton45;
    public javax.swing.JButton jButton46;
    public javax.swing.JButton jButton47;
    public javax.swing.JButton jButton48;
    public javax.swing.JButton jButton49;
    public javax.swing.JButton jButton50;
    public javax.swing.JButton jButton51;
    public javax.swing.JButton jButton52;
    public javax.swing.JButton jButton53;
    public javax.swing.JButton jButton54;
    public javax.swing.JButton jButton55;
    public javax.swing.JButton jButton56;
    public javax.swing.JButton jButton57;
    public javax.swing.JButton jButton58;
    public javax.swing.JButton jButton59;
    public javax.swing.JButton jButton60;
    public javax.swing.JButton jButton61;
    public javax.swing.JButton jButton62;
    public javax.swing.JButton jButton63;
    public javax.swing.JButton jButton64;
    public javax.swing.JButton jButton65;
    public javax.swing.JButton jButton66;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelDecidir;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelPruebas;
    public javax.swing.JPanel panelSimbolos;
    private javax.swing.JPanel panelTablaTransicion;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JScrollPane scrollTablaPruebas;
    public javax.swing.JTable tablaPruebas;
    // End of variables declaration//GEN-END:variables
  
}
